### ISSUE TITLE
No Icon on Kubuntu

### ISSUE THREAD

**Issue by firefoxlover** [flathub/dev.alextren.Spot#3]
Only the generic "X" icon is displayed.

Version: flatpak 10.11.21 (stable)

Kernel Version: 5.13.0-25-generic(64bit)
Qt-Version: 5.15.2
KDE-Plasma Version: 5.22.5
KDE-Frameworks Version: 5.86.0

**Comment by xou816** [comment]
Hmm, that's weird! Couple of questions:
- do you have any other DE on your system to test if it's KDE related?
- have you had any previous installation of Spot on your system that might conflict with this one? (if so, check ~/.local/share/applications for older desktop entries for Spot)
- have you had this issue in the past with other flatpak applications?
