### ISSUE TITLE
No / not working hover-control

### ISSUE THREAD

**Issue by firefoxlover** [flathub/dev.alextren.Spot#4]
When hovering over the icon, there is no hover conrol for start/stop, skip, previous.

This would be a really nice addition!

Version: flatpak 10.11.21 (stable)

Kernel Version: 5.13.0-25-generic(64bit)
Qt-Version: 5.15.2
KDE-Plasma Version: 5.22.5
KDE-Frameworks Version: 5.86.0

**Comment by xou816** [comment]
Hi! Thanks for the suggestion. That would be nice indeed! In the future, could you report issues in the main repo however? (xou816/spot). Thanks!
