### ISSUE TITLE
Stable version on Flathub lagging behind?

### ISSUE THREAD

**Issue by kkeijzer** [flathub/dev.alextren.Spot#7]
The last release seems to be 0.3.3: https://github.com/xou816/spot/releases/tag/0.3.3

But the version on Flathub is 0.3.1.

**Comment by bbhtt** [comment]
It's 0.3.3 https://github.com/flathub/dev.alextren.Spot/blob/2b0e1fbc67499d3a715390772c1fde28cbcaffeb/dev.alextren.Spot.json#L50-L51

**Comment by xou816** [comment]
no you're right sorry, something is weird! flathub lists 0.3.1 as the latest still
